name: Wdrożenie na GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Instalacja zależności
        run: npm ci

      - name: Budowanie aplikacji
        run: npm run build:gh

      - name: Wdrożenie na GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy:gh -- --no-silent --name "GitHub Actions" --email "actions@github.com"
